### ISSUE TITLE
leaving behing go < 1.7 ?

### ISSUE THREAD

**Issue by mro** [bogem/id3v2#24]
somewhen between now and 14 days ago you dropped support for go 1.5 and 1.6. Is this by intention or accident?

Thx,
    m

(I'm using it in https://travis-ci.org/mro/internet-radio-recorder/builds/228106947)

**Comment by bogem** [comment]
Hi, @mro!
Yes, I made it by intention to support only last two version of go. [This](https://github.com/bogem/id3v2/commit/3a13c042c0afbbd4a94cf2e001b3a6b8c32d3a51#diff-a134d6dc85ee994237dc23c6710217bb) is the only breaking change.
If you really need to support older versions, I can restore it.

**Comment by mro** [comment]
actually backwards compatibility isn't a major issue and I was just wondering. Having it is nice, but only as long as it doesn't stand in the way.

**Comment by bogem** [comment]
It actually doesn't stand in the way. The only issue that breaks the compatibility is what I decided to `io.SeekStart` instead of `os.SEEK_SET`  [here](https://github.com/bogem/id3v2/commit/3a13c042c0afbbd4a94cf2e001b3a6b8c32d3a51#diff-a134d6dc85ee994237dc23c6710217bb), so it's not the problem actually.
